package com.layoutxml.sabs.model;

import java.util.ArrayList;
import java.util.List;

public class AdhellPermissionInfo {
    public final String name;
    public final String label;

    public AdhellPermissionInfo(String name, String label) {
        this.name = name;
        this.label = label;

    }

    public static List<AdhellPermissionInfo> loadPermissions() {

        List<AdhellPermissionInfo> lis = new ArrayList<>();
        lis.add(new AdhellPermissionInfo("android.permission.ACCESS_CHECKIN_PROPERTIES","允许程序读取或写入登记check-in数据库属性表的权限, 更改值后上传."));
        lis.add(new AdhellPermissionInfo("android.permission.ACCESS_COARSE_LOCATION","允许程序通过WiFi或移动基站的方式获取用户错略的经纬度信息."));
        lis.add(new AdhellPermissionInfo("android.permission.ACCESS_FINE_LOCATION","允许程序通过GPS芯片接收卫星的定位信息."));
        lis.add(new AdhellPermissionInfo("android.permission.ACCESS_LOCATION_EXTRA_COMMANDS","允许程序访问额外的定位提供者指令."));
        lis.add(new AdhellPermissionInfo("android.permission.ACCESS_NETWORK_STATE","允许程序获取网络信息状态，如当前的网络连接是否有效."));
        lis.add(new AdhellPermissionInfo("android.permission.ACCESS_NOTIFICATION_POLICY","标记想要访问通知正常的应用权限."));
        lis.add(new AdhellPermissionInfo("android.permission.ACCESS_WIFI_STATE","允许程序获取当前WiFi接入的状态以及WLAN热点的信息."));
        lis.add(new AdhellPermissionInfo("android.permission.ACCOUNT_MANAGER","允许程序获取账户验证信息，主要为GMail账户信息，只有系统级进程才能访问的权."));
        lis.add(new AdhellPermissionInfo("com.android.voicemail.permission.ADD_VOICEMAIL","允许应用程序添加语音邮件到系统中."));
        lis.add(new AdhellPermissionInfo("android.permission.ANSWER_PHONE_CALLS","允许应用程序接听来电."));
        lis.add(new AdhellPermissionInfo("android.permission.BATTERY_STATS","允许程序获取电池电量统计信息"));
        lis.add(new AdhellPermissionInfo("android.permission.BIND_ACCESSIBILITY_SERVICE","必须要一个要求AccessibilityService, 以确保只有系统能绑定它."));
        lis.add(new AdhellPermissionInfo("android.permission.BIND_APPWIDGET","允许程序告诉appWidget服务需要访问小插件的数据库，只有非常少的应用才用到此权限."));
        lis.add(new AdhellPermissionInfo("android.permission.BIND_AUTOFILL_SERVICE","必须要一个要求AutofillService, 以确保只有系统能绑定它."));
        lis.add(new AdhellPermissionInfo("android.permission.BIND_CARRIER_MESSAGING_SERVICE","此常量在API level 23中已启用. 请改用BIND_CARRIER_SERVICES"));
        lis.add(new AdhellPermissionInfo("android.permission.BIND_CARRIER_SERVICES","即允许绑定到服务运营商的应用程序都会有此权限的系统进程."));
        lis.add(new AdhellPermissionInfo("android.permission.BIND_CHOOSER_TARGET_SERVICE","必须由被要求ChooserTargetService，以确保只有系统可以绑定到它."));
        lis.add(new AdhellPermissionInfo("android.permission.BIND_CONDITION_PROVIDER_SERVICE","必须由被要求ConditionProviderService，以确保只有系统可以绑定到它."));
        lis.add(new AdhellPermissionInfo("android.permission.BIND_DEVICE_ADMIN","必须有设备管理接收器是必需的，以确保只有系统可以与它进行交互."));
        lis.add(new AdhellPermissionInfo("android.permission.BIND_DREAM_SERVICE","必须有一个要求DreamService，以确保只有系统可以绑定到它."));
        lis.add(new AdhellPermissionInfo("android.permission.BIND_INCALL_SERVICE","必须有一个要求InCallService，以确保只有系统可以绑定到它."));
        lis.add(new AdhellPermissionInfo("android.permission.BIND_INPUT_METHOD","必须用一个要求InputMethodService，以确保只有系统可以绑定到它."));
        lis.add(new AdhellPermissionInfo("android.permission.BIND_MIDI_DEVICE_SERVICE","必须用一个要求MidiDeviceService，以确保只有系统可以绑定到它."));
        lis.add(new AdhellPermissionInfo("android.permission.BIND_NFC_SERVICE","必须有一个要求HostApduService 或者OffHostApduService以确保只有系统可以绑定到它."));
        lis.add(new AdhellPermissionInfo("android.permission.BIND_NOTIFICATION_LISTENER_SERVICE","必须用一个要求NotificationListenerService，以确保只有系统可以绑定到它."));
        lis.add(new AdhellPermissionInfo("android.permission.BIND_PRINT_SERVICE","必须有一个要求PrintService，以确保只有系统可以绑定到它."));
        lis.add(new AdhellPermissionInfo("android.permission.BIND_QUICK_SETTINGS_TILE","允许绑定到第三方快速设置磁贴的应用程序."));
        lis.add(new AdhellPermissionInfo("android.permission.BIND_REMOTEVIEWS","必须有一个要求RemoteViewsService，以确保只有系统可以绑定到它."));
        lis.add(new AdhellPermissionInfo("android.permission.BIND_SCREENING_SERVICE","必须有一个要求CallScreeningService，以确保只有系统可以绑定到它."));
        lis.add(new AdhellPermissionInfo("android.permission.BIND_TELECOM_CONNECTION_SERVICE","必须有一个要求ConnectionService，以确保只有系统可以绑定到它."));
        lis.add(new AdhellPermissionInfo("android.permission.BIND_TEXT_SERVICE","必须有一个TextService要求"));
        lis.add(new AdhellPermissionInfo("android.permission.BIND_TV_INPUT","必须有一个要求TvInputService 以确保只有系统可以绑定到它."));
        lis.add(new AdhellPermissionInfo("android.permission.BIND_VISUAL_VOICEMAIL_SERVICE","必须有一个链接要求VisualVoicemailService，以确保只有系统可以绑定到它."));
        lis.add(new AdhellPermissionInfo("android.permission.BIND_VOICE_INTERACTION","必须有一个要求VoiceInteractionService，以确保只有系统可以绑定到它."));
        lis.add(new AdhellPermissionInfo("android.permission.BIND_VPN_SERVICE","必须有一个要求VpnService，以确保只有系统可以绑定到它."));
        lis.add(new AdhellPermissionInfo("android.permission.BIND_VR_LISTENER_SERVICE","必须有一个VrListenerService，以确保只有系统可以绑定到它."));
        lis.add(new AdhellPermissionInfo("android.permission.BIND_WALLPAPER","必须有一个要求WallpaperService，以确保只有系统可以绑定到它."));
        lis.add(new AdhellPermissionInfo("android.permission.BLUETOOTH","允许程序连接配对过的蓝牙设备."));
        lis.add(new AdhellPermissionInfo("android.permission.BLUETOOTH_ADMIN","允许程序进行发现和配对新的蓝牙设备."));
        lis.add(new AdhellPermissionInfo("android.permission.BLUETOOTH_PRIVILEGED","允许应用程序配对的蓝牙设备而无需用户交互，以及允许或不允许访问电话簿或消息的访问."));
        lis.add(new AdhellPermissionInfo("android.permission.BODY_SENSORS","允许应用程序访问用户用来测量他/她身体内发生的事情的传感器的数据，例如心率传感器."));
        lis.add(new AdhellPermissionInfo("android.permission.BROADCAST_PACKAGE_REMOVED","允许程序删除时广播."));
        lis.add(new AdhellPermissionInfo("android.permission.BROADCAST_SMS","允许程序当收到短信时触发一个广播."));
        lis.add(new AdhellPermissionInfo("android.permission.BROADCAST_STICKY","允许程序收到广播后快速收到下一个广播."));
        lis.add(new AdhellPermissionInfo("android.permission.BROADCAST_WAP_PUSH","WAP PUSH服务收到后触发一个广播."));
        lis.add(new AdhellPermissionInfo("android.permission.CALL_PHONE","允许程序从非系统拨号器里拨打电话."));
        lis.add(new AdhellPermissionInfo("android.permission.CALL_PRIVILEGED","允许程序拨打电话，替换系统的拨号器界面."));
        lis.add(new AdhellPermissionInfo("android.permission.CAMERA","允许程序访问摄像头进行拍照."));
        lis.add(new AdhellPermissionInfo("android.permission.CAPTURE_AUDIO_OUTPUT","允许应用程序捕获音频输出."));
        lis.add(new AdhellPermissionInfo("android.permission.CAPTURE_SECURE_VIDEO_OUTPUT","允许应用程序捕获安全视频输出."));
        lis.add(new AdhellPermissionInfo("android.permission.CAPTURE_VIDEO_OUTPUT","允许应用程序捕获视频输出."));
        lis.add(new AdhellPermissionInfo("android.permission.CHANGE_COMPONENT_ENABLED_STATE","改变组件是否启用状态"));
        lis.add(new AdhellPermissionInfo("android.permission.CHANGE_CONFIGURATION","允许当前应用改变配置，如定位."));
        lis.add(new AdhellPermissionInfo("android.permission.CHANGE_NETWORK_STATE","允许程序改变网络状态,如是否联网."));
        lis.add(new AdhellPermissionInfo("android.permission.CHANGE_WIFI_MULTICAST_STATE","允许程序改变WiFi多播状态."));
        lis.add(new AdhellPermissionInfo("android.permission.CHANGE_WIFI_STATE","允许程序改变WiFi状态."));
        lis.add(new AdhellPermissionInfo("android.permission.CLEAR_APP_CACHE","允许程序清除已安装应用缓存."));
        lis.add(new AdhellPermissionInfo("android.permission.CONTROL_LOCATION_UPDATES","允许程序获得移动网络定位信息改变."));
        lis.add(new AdhellPermissionInfo("android.permission.DELETE_CACHE_FILES","允许程序删除缓存文件."));
        lis.add(new AdhellPermissionInfo("android.permission.DELETE_PACKAGES","允许程序删除应用."));
        lis.add(new AdhellPermissionInfo("android.permission.DIAGNOSTIC","允许程序到RW到诊断资源."));
        lis.add(new AdhellPermissionInfo("android.permission.DISABLE_KEYGUARD","允许程序禁用键盘锁."));
        lis.add(new AdhellPermissionInfo("android.permission.DUMP","允许程序获取系统dump信息从系统服务."));
        lis.add(new AdhellPermissionInfo("android.permission.EXPAND_STATUS_BAR","允许程序扩展或收缩状态栏."));
        lis.add(new AdhellPermissionInfo("android.permission.FACTORY_TEST","允许程序运行工厂测试模式，以root用户运行."));
        lis.add(new AdhellPermissionInfo("android.permission.GET_ACCOUNTS","允许程序访问账户列表."));
        lis.add(new AdhellPermissionInfo("android.permission.GET_ACCOUNTS_PRIVILEGED","允许访问的帐户服务帐户列表."));
        lis.add(new AdhellPermissionInfo("android.permission.GET_PACKAGE_SIZE","允许程序获取应用的文件大小."));
        lis.add(new AdhellPermissionInfo("android.permission.GET_TASKS","已在API level 21弃用，不再强制执行."));
        lis.add(new AdhellPermissionInfo("android.permission.GLOBAL_SEARCH","此权限可用于内容提供商以允许全局搜索系统访问其数据."));
        lis.add(new AdhellPermissionInfo("android.permission.INSTALL_LOCATION_PROVIDER","允许应用程序安装一个位置提供程序安装到位置管理器中."));
        lis.add(new AdhellPermissionInfo("android.permission.INSTALL_PACKAGES","允许程序安装应用."));
        lis.add(new AdhellPermissionInfo("com.android.launcher.permission.INSTALL_SHORTCUT","允许程序创建快捷方式."));
        lis.add(new AdhellPermissionInfo("android.permission.INSTANT_APP_FOREGROUND_SERVICE","允许即时应用创建前台服务."));
        lis.add(new AdhellPermissionInfo("android.permission.INTERNET","允许程序访问网络连接，可能产生GPRS流量."));
        lis.add(new AdhellPermissionInfo("android.permission.KILL_BACKGROUND_PROCESSES","允许程序调用killBackgroundProcesses(String).方法结束后台进程."));
        lis.add(new AdhellPermissionInfo("android.permission.LOCATION_HARDWARE","允许使用在硬件位置的功能，如在区域范围设定API的应用程序."));
        lis.add(new AdhellPermissionInfo("android.permission.MANAGE_DOCUMENTS","允许应用程序来管理存取文件，通常作为文档选择器的一部分."));
        lis.add(new AdhellPermissionInfo("android.permission.MANAGE_OWN_CALLS","允许通过自我管理的ConnectionService API管理自己的调用的调用应用程序."));
        lis.add(new AdhellPermissionInfo("android.permission.MASTER_CLEAR","允许程序执行软格式化，删除系统配置信息."));
        lis.add(new AdhellPermissionInfo("android.permission.MEDIA_CONTENT_CONTROL","允许应用程式知道正在播放的内容并控制其播放."));
        lis.add(new AdhellPermissionInfo("android.permission.MODIFY_AUDIO_SETTINGS","允许应用修改全局音频设置."));
        lis.add(new AdhellPermissionInfo("android.permission.MODIFY_PHONE_STATE","允许程序修改电话状态，如飞行模式，但不包含替换系统拨号器界面."));
        lis.add(new AdhellPermissionInfo("android.permission.MOUNT_FORMAT_FILESYSTEMS","允许程序格式化可移动文件系统，比如格式化清空SD卡."));
        lis.add(new AdhellPermissionInfo("android.permission.MOUNT_UNMOUNT_FILESYSTEMS","允许程序挂载、反挂载外部文件系统."));
        lis.add(new AdhellPermissionInfo("android.permission.NFC","允许程序执行NFC近距离通讯操作，用于移动支持."));
        lis.add(new AdhellPermissionInfo("android.permission.PACKAGE_USAGE_STATS","允许应用程序收集组件使用情况统计信息"));
        lis.add(new AdhellPermissionInfo("android.permission.PERSISTENT_ACTIVITY","此常量在API级别9中已弃用。此功能将在未来删除; 请不要使用.允许应用程序使其活动持久化 ."));
        lis.add(new AdhellPermissionInfo("android.permission.PROCESS_OUTGOING_CALLS","允许程序监视，修改或放弃播出电话."));
        lis.add(new AdhellPermissionInfo("android.permission.READ_CALENDAR","允许程序读取用户的日程信息."));
        lis.add(new AdhellPermissionInfo("android.permission.READ_CALL_LOG","允许程序读取用户的通话记录."));
        lis.add(new AdhellPermissionInfo("android.permission.READ_CONTACTS","允许程序访问联系人通讯录信息."));
        lis.add(new AdhellPermissionInfo("android.permission.READ_EXTERNAL_STORAGE","允许程序读取设备外部存储空间（内置SDcard和外置SDCard)."));
        lis.add(new AdhellPermissionInfo("android.permission.READ_FRAME_BUFFER","允许程序读取帧缓存用于屏幕截图."));
        lis.add(new AdhellPermissionInfo("android.permission.READ_INPUT_STATE","此常量在API level 16已启用. 使用此权限的API已删除."));
        lis.add(new AdhellPermissionInfo("android.permission.READ_LOGS","允许程序读取系统底层日志."));
        lis.add(new AdhellPermissionInfo("android.permission.READ_PHONE_NUMBERS","允许读取设备的电话号码."));
        lis.add(new AdhellPermissionInfo("android.permission.READ_PHONE_STATE","允许只读访问电话状态，包括设备的电话号码，当前蜂窝网络信息，任何正在进行的呼叫的状态以及设备上注册的任何PhoneAccounts的列表."));
        lis.add(new AdhellPermissionInfo("android.permission.READ_SMS","允许程序读取短信内容."));
        lis.add(new AdhellPermissionInfo("android.permission.READ_SYNC_SETTINGS","允许程序读取同步设置."));
        lis.add(new AdhellPermissionInfo("android.permission.READ_SYNC_STATS","允许程序读取同步状态."));
        lis.add(new AdhellPermissionInfo("com.android.voicemail.permission.READ_VOICEMAIL","允许应用程序读取系统中的语音邮件."));
        lis.add(new AdhellPermissionInfo("android.permission.REBOOT","允许程序重新启动设备."));
        lis.add(new AdhellPermissionInfo("android.permission.RECEIVE_BOOT_COMPLETED","允许程序开机自动运行."));
        lis.add(new AdhellPermissionInfo("android.permission.RECEIVE_MMS","允许程序接收彩信."));
        lis.add(new AdhellPermissionInfo("android.permission.RECEIVE_SMS","允许程序接收短信."));
        lis.add(new AdhellPermissionInfo("android.permission.RECEIVE_WAP_PUSH","允许程序接收WAP PUSH信息."));
        lis.add(new AdhellPermissionInfo("android.permission.RECORD_AUDIO","允许程序录制声音通过手机或耳机的麦克."));
        lis.add(new AdhellPermissionInfo("android.permission.REORDER_TASKS","允许程序重新排序系统Z轴运行中的任务."));
        lis.add(new AdhellPermissionInfo("android.permission.REQUEST_COMPANION_RUN_IN_BACKGROUND","允许配套应用在后台运行."));
        lis.add(new AdhellPermissionInfo("android.permission.REQUEST_COMPANION_USE_DATA_IN_BACKGROUND","允许配套应用在后台使用数据."));
        lis.add(new AdhellPermissionInfo("android.permission.REQUEST_DELETE_PACKAGES","允许应用程序请求删除软件包."));
        lis.add(new AdhellPermissionInfo("android.permission.REQUEST_IGNORE_BATTERY_OPTIMIZATIONS","为了使用ACTION_REQUEST_IGNORE_BATTERY_OPTIMIZATIONS，应用程序必须拥有权限."));
        lis.add(new AdhellPermissionInfo("android.permission.REQUEST_INSTALL_PACKAGES","允许应用程序请求安装软件包."));
        lis.add(new AdhellPermissionInfo("android.permission.RESTART_PACKAGES","允许程序结束任务通过restartPackage(String)方法，该方式将在外来放弃."));
        lis.add(new AdhellPermissionInfo("android.permission.SEND_RESPOND_VIA_MESSAGE","允许应用程序（电话）向其他应用程序发送请求以处理传入呼叫期间的响应通过消息操作."));
        lis.add(new AdhellPermissionInfo("android.permission.SEND_SMS","允许程序发送短信."));
        lis.add(new AdhellPermissionInfo("com.android.alarm.permission.SET_ALARM","允许程序设置闹铃提醒."));
        lis.add(new AdhellPermissionInfo("android.permission.SET_ALWAYS_FINISH","允许程序设置程序在后台是否总是退出."));
        lis.add(new AdhellPermissionInfo("android.permission.SET_ANIMATION_SCALE","允许程序设置全局动画缩放."));
        lis.add(new AdhellPermissionInfo("android.permission.SET_DEBUG_APP","允许程序设置调试程序，一般用于开发."));
        lis.add(new AdhellPermissionInfo("android.permission.SET_PREFERRED_APPLICATIONS","允许程序设置应用的参数，已不再工作具体查看addPackageToPreferred(String) 介绍."));
        lis.add(new AdhellPermissionInfo("android.permission.SET_PROCESS_LIMIT","允许程序设置最大的进程数量的限制."));
        lis.add(new AdhellPermissionInfo("android.permission.SET_TIME","允许程序设置系统时间."));
        lis.add(new AdhellPermissionInfo("android.permission.SET_TIME_ZONE","允许程序设置系统时区."));
        lis.add(new AdhellPermissionInfo("android.permission.SET_WALLPAPER","允许程序设置桌面壁纸."));
        lis.add(new AdhellPermissionInfo("android.permission.SET_WALLPAPER_HINTS","允许程序设置壁纸建议."));
        lis.add(new AdhellPermissionInfo("android.permission.SIGNAL_PERSISTENT_PROCESSES","允许程序发送一个永久的进程信号."));
        lis.add(new AdhellPermissionInfo("android.permission.STATUS_BAR","允许程序打开、关闭、禁用状态栏."));
        lis.add(new AdhellPermissionInfo("android.permission.SYSTEM_ALERT_WINDOW","允许程序显示系统窗口."));
        lis.add(new AdhellPermissionInfo("android.permission.TRANSMIT_IR","允许使用设备的红外发射器（如果可用）."));
        lis.add(new AdhellPermissionInfo("com.android.launcher.permission.UNINSTALL_SHORTCUT","此权限不再受支持."));
        lis.add(new AdhellPermissionInfo("android.permission.UPDATE_DEVICE_STATS","允许程序更新设备状态."));
        lis.add(new AdhellPermissionInfo("android.permission.USE_FINGERPRINT","允许应用使用指纹硬件."));
        lis.add(new AdhellPermissionInfo("android.permission.USE_SIP","允许程序使用SIP视频服务."));
        lis.add(new AdhellPermissionInfo("android.permission.VIBRATE","允许程序振动."));
        lis.add(new AdhellPermissionInfo("android.permission.WAKE_LOCK","允许程序在手机屏幕关闭后后台进程仍然运行."));
        lis.add(new AdhellPermissionInfo("android.permission.WRITE_APN_SETTINGS","允许程序写入网络GPRS接入点设置."));
        lis.add(new AdhellPermissionInfo("android.permission.WRITE_CALENDAR","允许应用程序写入用户的日历数据."));
        lis.add(new AdhellPermissionInfo("android.permission.WRITE_CALL_LOG","允许程序写入（但是不能读）用户的联系人数据."));
        lis.add(new AdhellPermissionInfo("android.permission.WRITE_CONTACTS","允许程序写入联系人，但不可读取."));
        lis.add(new AdhellPermissionInfo("android.permission.WRITE_EXTERNAL_STORAGE","允许程序写入外部存储，如SD卡上写文件."));
        lis.add(new AdhellPermissionInfo("android.permission.WRITE_GSERVICES","允许程序写入Google Map服务数据."));
        lis.add(new AdhellPermissionInfo("android.permission.WRITE_SECURE_SETTINGS","允许程序读写系统安全敏感的设置项."));
        lis.add(new AdhellPermissionInfo("android.permission.WRITE_SETTINGS","允许程序读写系统设置项."));
        lis.add(new AdhellPermissionInfo("android.permission.WRITE_SYNC_SETTINGS","允许应用程序写入同步设置."));
        lis.add(new AdhellPermissionInfo("com.android.voicemail.permission.WRITE_VOICEMAIL","允许应用修改和删除系统中现有的语音邮件."));

        return lis;
    }
}
